### ISSUE TITLE
iPad Shuttles - Overlayed stop annotations

### ISSUE THREAD

**Issue by LoganWright** [MIT-Mobile/MIT-Mobile-for-iPhone#638]
Intersecting stops annotations appear to have have a very thick shadow because they are being layed out on top of each other.

Perhaps add something to prevent duplicating an annotation.

**Comment by Smartcop** [comment]
@justinanderson 
Re @LoganWright 

Let's say I am on the iPad and I select MIT Museum.  Both Saferide Cambridge All and Saferide Boston West have a stop here.  It only shows Saferide Boston West.  

When I remove this fix and click on the same annotation again I get Saferide Cambridge All.  That's why there are multiple annotations.

Would should be the solution?

![ios simulator screen shot jan 7 2015 6 20 43 pm](https://cloud.githubusercontent.com/assets/1474560/5655257/eaeaa5fa-9699-11e4-8d5d-07a013262be7.png)

**Comment by LoganWright** [comment]
@Smartcop - MIT Museum doesn't show as a stop on Saferide Cambridge All for me -- 

<b>Boston West -- MIT Museum Included</b>

![ios simulator screen shot jan 8 2015 9 22 05 am](https://cloud.githubusercontent.com/assets/5750489/5663677/eee52fbc-9717-11e4-9330-d01b88d34339.png)

<b>Saferide Boston All -- No MIT Museum stop listed</b>

![ios simulator screen shot jan 8 2015 9 22 17 am](https://cloud.githubusercontent.com/assets/5750489/5663694/0f613470-9718-11e4-8c06-94774f2f3d52.png)

![ios simulator screen shot jan 8 2015 9 22 15 am](https://cloud.githubusercontent.com/assets/5750489/5663696/14ae15c4-9718-11e4-8f0b-faf0261ae7eb.png)

Is MIT Museum definitely supposed to be a stop on Saferide Boston All?

We can remove the code to prevent duplicate annotations, the only issue is that stops with multiple routes look much bolder.  Would you prefer to leave it like that?

**Comment by Smartcop** [comment]
You are selecting Saferide Boston All instead of Saferide Cambridge All.

I agree the stops in this sidebar are not affected.  I am selecting an annotation from the main All Routes screen.

The issue of not removing the duplicate annotation is when we select an annotation we are only getting Saferide Boston West in the popover and not both Saferide Boston West and Saferide Cambridge All.

I do not know the correct action because keeping the code in gets rid of routes that should be at that stop but as the same time if we get rid of the code no one is going to know to keep on selecting that "same" annotation even though its going to show different results 

@LoganWright 
@justinanderson

**Comment by LoganWright** [comment]
@Smartcop - We can make sure that all the intersecting routes show if that's the only issue.

**Comment by Smartcop** [comment]
@LoganWright 
Yep that is my current issue.

**Comment by LoganWright** [comment]
@Smartcop - Ok, I'll make sure the intersecting routes are showing, that way we can have the annotations look good and a user doesn't have to select multiple annotations in the same stop.

Here's the behavior I think would work.

If I select annotation from the map, show all routes in popover.
If I select annotation from sidebar, show all routes except the route from selected.

Sound good?

**Comment by Smartcop** [comment]
@LoganWright 
Great!

**Comment by Smartcop** [comment]
:+1:
