### ISSUE TITLE
Shuttles predictions sticking around after they go stale

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#671]
Shuttles predictions stick around even after they go stale. Can be reproduced by starting the app with cached times but no internet connection, possibly other ways as well.

**Comment by justinanderson** [comment]
@Smartcop I think this is correct behavior. If the latest predictions are less than 60 seconds old, they're still valid.

Are you seeing predictions stick around longer than a minute?

**Comment by Smartcop** [comment]
@justinanderson Yep the predictions are sticking around indefinitely.

**Comment by rosslebeau** [comment]
@justinanderson I just noticed this: If the route info web call fails, the routes will stay in their previous state forever. I've fixed it so the predictions will show "-" after 60 seconds, but the route will stay showing as active as long as the user doesn't have an internet connection. This seems like it could cause people to think shuttles are running when they're not, but I'm not sure when is an appropriate time to set all the routes to inactive, or at least display them as such, or if we should even do that. Thoughts?

**Comment by justinanderson** [comment]
@rosslebeau The predictable flag should both be considered invalid after 60 seconds and default to false, but it's ok for the scheduled flag to not expire since predictable is what decides if a route is in service. So, anything scheduled but with stale predictions would end up appearing in the unknown state, and anything not scheduled but with fresh predictions would appear as in service.

If you turn a route's predictable flag to false when you expire its predictions, that should do it.

Predictable really means it has active vehicles, and sometimes stops on an active route won't have predictions because the route it ending soon, so it's possible that a route could be predictable without having any predictions. So as long as it just staleness that invalidates predictable and not "anytime we show —", that should do it.

**Comment by rosslebeau** [comment]
@justinanderson I understand the logic now, but I think there are a couple practical concerns for the UI. For one, I now think we should keep the "all routes" call currently on the home screen going every 60 seconds as long as the user is in the shuttles module. That way there won't be any delay where the user switches to another route or returns to the home screen and sees inactive states for 0.x seconds while we make the web call to update. I think this is ok for predictions staleness because we just show "—" for a second or two and people understand that those are frequently-updated, but having routes switching their active state and jumping around the tableview would be jarring.

Another thing is that having both an update time and staleness limit of 60 seconds means that there will always be "stale" data while we are making the update requests. We can't simply wait to update the UI until the call returns because, in an effort to make more efficient use of our bandwidth, we are making aggregate predictions and vehicles calls independently from the route calls, and these returning will trigger a UI update. I think simply using a larger staleness delay is a satisfactory solution (maybe 80 seconds)?

There aren't huge problems, but I'm deferring to you because I want to make sure the app behavior is how you envision it.

**Comment by justinanderson** [comment]
@rosslebeau http://m.mit.edu/apis/shuttles/routes/ is a big response to be polling. If the concern is to keep the predictable and scheduled flags fresh, http://m.mit.edu/apis/shuttles/vehicles/ would accomplish that with a faster response. It includes the predictable and scheduled flags for every route. Poll /apis/shuttles/vehicles/ every 60 seconds on the iPhone Shuttles home screen and boost the staleness delay to 90 just to be safe?

On the iPad, we're already polling for all vehicles since the map is always visible, so we'd just need to make sure that all calls for /apis/shuttles/vehicles/ update the predictable and scheduled flags of routes.

**Comment by rosslebeau** [comment]
@justinanderson Ah yeah I forgot that other calls also had the predictable and scheduled flags. Great, I'll add the http://m.mit.edu/apis/shuttles/vehicles/ polling at 60 seconds to the iphone, consider routes stale and therefore `predictable == NO` after 90 seconds, and make sure the models and UI are updating properly.

**Comment by rosslebeau** [comment]
@justinanderson in order to directly map the `predictable` and `scheduled` flags to the ShuttleRoute from various web calls, I am trying to add an additional RKEntityMapping for the nil (base) keypath. E.g. for PredictionLists, I want to add a RKEntityMapping for ShuttleRoute that uses the `route_id` as the identifier, and takes the `predictable` and `scheduled` keys directly from the base PredictionList dictionary, and updates the ShuttleRoute entity with those.

In MITMobileResource, there is an NSAssert that disallows the adding of multiple mappings to the nil keypath. Is there a reason this is bad that I am unaware of?

I'm pretty sure I can accomplish this in another manner, just wondering what the deal is with that.

**Comment by rosslebeau** [comment]
@justinanderson As a secondary note, it appears that the production server is not returning the `predictable` and `scheduled` keys for objects in the `/shuttles/predictions/` path.

**Comment by justinanderson** [comment]
@rosslebeau I don't know of a reason for that NSAssert, but I imagine @bskinner would know.

The `predictable` and `scheduled` keys are being returned on mobile-dev, but not on production yet.

**Comment by bskinner** [comment]
@rosslebeau That looks like it was due to the odd way I was keeping track of the mappings. I have a fix proposed in the '3.6/object-mapping-tweaks' branch; let me know how if it works for you!

**Comment by rosslebeau** [comment]
@bskinner Aha! It did indeed work, and it exposed a pretty good reason why I actually don't want to do it that way. Although we may want to use this in the future, adding a mapping to the resource like that means that the web calls will return objects of both types (in this case, PredictionLists and ShuttleRoutes). We really only want PredictionLists to be returned, even though we want to make sure ShuttleRoutes are updated.

I think I can accomplish this using relationship mappings from PredictionList -> ShuttleStop -> ShuttleRoute, so I'll give that a shot. Thanks for the help...RestKit is quite complex, and I have only recently started digging into it.

**Comment by rosslebeau** [comment]
@justinanderson On my branch, routes are now updating their predictable and scheduled flags from predictions and vehicles calls, and have a timestamp to know when they were last updated and determine staleness.

I noticed a discrepancy in the web services that sometimes makes one of the routes show the wrong UI: the `evening` route has `predictable = true` at this URL:
https://mobile-dev.mit.edu/apis/shuttles/predictions/?agency=charles-river&stops=evening%2Ctech200

and `predictable = false` at this URL:
https://mobile-dev.mit.edu/apis/shuttles/predictions/?agency=mit&stops=boston%2Cmass77

**Comment by rosslebeau** [comment]
@justinanderson There are more discrepancies in the predictable flag across web calls, so the UI is often funky (routes shifting between states often), but this should all be fixed when the web calls are the same:

This time the vehicles call (https://mobile-dev.mit.edu/apis/shuttles/vehicles/) is returning `predictable = true` for `kendchar`, and the predictions call here (https://mobile-dev.mit.edu/apis/shuttles/predictions/?agency=mit&stops=boston%2Cmass77%3Btech%2Cvassmass%3Bkendchar%2Cwadse40) is returning `predictable = false`

**Comment by justinanderson** [comment]
@rosslebeau Ok. I'm pretty sure that's a caching issue on our server.

**Comment by justinanderson** [comment]
:+1:
