### ISSUE TITLE
Libraries Locations and Hours

### ISSUE THREAD

**Issue by Smartcop** [MIT-Mobile/MIT-Mobile-for-iPhone#739]
Would be nice for it to store locations and hours offline to access later.  Currently making request every time we open view.

**Comment by LoganWright** [comment]
@Smartcop - From what I can see, this part of libraries isn't hooked up to core data at all and it would be a bit more to convert the objects to NSManagedObjects and all related webcalls etc.  I changed the workflow of the libraries screen a little bit so that it doesn't destroy the VC each time and the webcall isn't made everytime you open the VC, only the first time.

**Comment by LoganWright** [comment]
Accidentally closed this by clicking the wrong button.

**Comment by justinanderson** [comment]
:+1:
